# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
